### ISSUE TITLE
1.4.0 with custom template does not display tab contents on initial load

### ISSUE THREAD

**Issue by skidvd** [rpocklin/ui-router-tabs#21]
I recently upgraded from 1.3.0 to 1.4.0 and starting encountering an issue where the default (first) tab contents are not displayed upon load.  Once you start clicking in the tab headings all is fine.  However, the initial load shows an empty tab.

Punk is here: http://plnkr.co/edit/wtTLfsaEppmlyDOAad0L

The same occurs when using the default template as well.  This did not occur in 1.3.0.

**Comment by rpocklin** [comment]
Yep you're right.  It's a breaking change, hence `v1.4.0` - check the release notes on the homepage.

Reason is not everyone wanted it, if you want the old behaviour (ie. default to the first tab) then deep link the page that displays the tabs.

Currently the default tab is highlighted anyway, which is a bug in `ui-bootstrap` which is fixed in master but not released, for more info see https://github.com/angular-ui/bootstrap/commit/91b5fb62eedbb600d6a6abe32376846f327a903d

**Comment by skidvd** [comment]
Doh!  Sorry I missed that.  Just curious, what motivated this change - seems like the defaulting (in the absence of a deep link) would be appropriate default?

**Comment by rpocklin** [comment]
It's in #16 but basically it's an assumption you always want to select the first tab.  In certain cases though, you may want to show all unselected tabs and make the user choose which tab they want (which will happen once the above bug is fixed).
