### ISSUE TITLE
Selecting a tab on load

### ISSUE THREAD

**Issue by Lighiche** [rpocklin/ui-router-tabs#30]
Great jobs works really well, one thing though given your example:

    <div class="row">
        <div class="col-md-12">
            <tabs data="tabData" type="tabs"></tabs>
        </div>

        <div class="col-md-12">
            <ui-view autoscroll>  </ui-view>
        </div>
    </div>

How would one select a tab by default? You say: "link the ui-view containing the tabs with the default (first) element as the sub-route example/#/user/settings in the example", In the Tips section, but I'm not sure how to apply this in practice. My '/' shows the tabs, and '/create' is my first tab that I'd like to select. Any help would be awesome.

**Comment by rpocklin** [comment]
This issue seems to come up a bit.  There's some more info https://github.com/rpocklin/ui-router-tabs/issues/28 basically the view that links to the tabbed view layout should not link to '/' but instead link to '/create' - for your case.  

Typically this is done via `$state.go` or a `ui-sref` link.

If you still are having problems, create a plunkr and i'll guide you through it.

**Comment by Lighiche** [comment]
Thanks for the reply. Having a bit or trouble finding a CDN for ui-router-tabs actually, but here's the plunker: http://plnkr.co/edit/tlt6p898fJZofqb1vkT9?p=preview this is close to what I have but can't get it exact without the module obviously. I tried copying it in direct but the directive threw and error.

**Comment by rpocklin** [comment]
There's a few issues there with invalid routes, etc, but i'd recommend not putting the tab on the index.html and inside an actual route, even if it's the default route.  Plunkrs with this stuff is hard because it plays with the url.  Can I suggest you modify the example to suit what you need and work off that as a base?

**Comment by Lighiche** [comment]
Yea sorry about that I didn't copy/paste the code I just rewrote it i've fixed some of the typos. What I have in my main project is 3 tabs showing none selected. Once selected they route, I don't mean to mislead you into thinking the problem is somewhere else. I've tried all the logical steps that I know to try, now I'm just poking and prodding. Like i said the Plunker cdn is 404ing on me for ui-router-tabs =[.

 So, my understanding is, I have a home page '/' right now, linking to a state that SHOWS that I have tabs, index.html, in which no specific tabs are set to active ( or can be set to active ). My page won't load without some top level route like  'tabbed', because children tabbed.create don't exist in that case. I have tabData, full of tabs, their headers and routes to the pages they display. Those routes link by state back to app.config child states of tabbed and their templateUrls. I've changed things in .config, in the controller and in the index.html page trying to get a tab to select by default. Am I misunderstanding how this works
My attempts to use ui-sref does work either. At this point i'm not sure where the change should be made xD index config or controller.

**Comment by rpocklin** [comment]
If you open the example up to a deeply nested route ie. `http://rp.js.org/ui-router-tabs/example/index.html#/user/settings/one` it will deep-link directly.  This is how to do it.  Also see in this file in the example `https://github.com/rpocklin/ui-router-tabs/blob/master/example/user/accounts.html` how it uses `ui-sref` or `ng-click` callback to achieve the same.  Hope this explains it for you.

**Comment by Lighiche** [comment]
Per sort of your instructions I did this:

    $scope.go = function (state) {
       $state.go(state); 
    }

and added 

    <ui-view ng-init="go(tabbed.createConsult)"></ui-view>

it routes to that tab but there is a brief moment where /#!/ loads before /#!/create is loaded. I from the beginning was trying to have it route directly there. Not sure if that's even possible any more lol.

**Comment by rpocklin** [comment]
That's because `ng-init` is only run once it parses the `ui-view` element.  This is not the way to do it.
Have the page that links to this one use the nested url.  I've given examples, if you don't understand i'm not sure I can help any more.  It may help to read up about ui-router and how it works a bit more.

**Comment by Lighiche** [comment]
Alright, will do, thanks
